listen_addresses = '*'
port = 5432
max_connections = 100

shared_buffers = 128MB
dynamic_shared_memory_type = posix

work_mem = 2GB

max_wal_size = 2GB
min_wal_size = 80MB

log_directory = 'pg_log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_statement = 'all'
logging_collector = 'on'

datestyle = 'iso'
timezone = 'UTC'
